---
- name: Update apt-cache
  apt: update_cache=yes 
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install build tools for Debian/Ubuntu
  apt: 
    name: ['build-essential', 'g++', 'gcc', 'make', 'cmake', 'libcurl4-openssl-dev', 'libboost-all-dev', 'libssl-dev', 'libtool', 'libtool-bin', 'autoconf', 'automake', 'zlib1g-dev', 'libgoogle-perftools-dev', 'git', 'curl', 'systemd-coredump', 'liblz4-tool']
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install build tools for CentOS/RedHat
  yum: 
    name: ['gcc', 'gcc-c++', 'make', 'cmake', 'git', 'autoconf', 'curl', 'libtool', 'openssl-devel', 'libcurl-devel', 'zlib-devel', 'boost-devel', 'gperftools-devel']
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: make source directory writeable
  file: path=/usr/local/src state=directory mode=0777

- name: check out drachtio-server 
  git: repo=https://github.com/drachtio/drachtio-server.git
       dest=/usr/local/src/drachtio-server
       version={{drachtioBranch}}
       depth=50
       accept_hostkey=yes
       force=yes
  become: no
  register: checkout

- name: Initialize and update git submodules
  command: git submodule update --init --recursive
  args:
    chdir: /usr/local/src/drachtio-server
  when: checkout.changed

- name: build drachtio-server
  shell: ./autogen.sh && mkdir -p build && cd $_ && ../configure CPPFLAGS='-DNDEBUG' && make && make install
  become: yes
  args:
    executable: /bin/bash
    chdir: /usr/local/src/drachtio-server/
    creates: /usr/local/src/drachtio-server/build/drachtio
  notify: restart drachtio
  when: checkout.changed

- name: Create drachtio log directories
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ drachtioLogFileDirectory }}"
    - "{{ drachtioLogArchiveDirectory }}"
  when: checkout.changed

- name: Create drachtio config file
  template:
    src: drachtio.conf.xml.j2
    dest: "/etc/drachtio.conf.xml"
    mode: 0644
    owner: root
    group: root
  notify: restart drachtio
  when: checkout.changed

- name: Create systemd unit file
  template:
    src: drachtio-systemd-script.j2
    dest: /etc/systemd/system/drachtio.service
    mode: 0644
    owner: root
    group: root
  notify: restart drachtio
  when: ansible_service_mgr == 'systemd' and checkout.changed

- name: systemctl daemon-reload
  shell: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd' and checkout.changed

- name: remove source code
  file: 
    path: /usr/local/src/drachtio-server
    state: absent
  when: remove_source|bool